----创建风险客户存储过程
CREATE OR REPLACE PROCEDURE SP_FK
IS
BEGIN
----清空风险客户表
EXECUTE IMMEDIATE 'TRUNCATE TABLE M_RISK_CUST_INFO';
--往风险客户表插入数据
INSERT INTO M_RISK_CUST_INFO

SELECT 
DKKB.ECIF_CUST_NO
,DKKB.CUST_NAME
,DKKB.MRG_STS
,DKKB.COU_CERT_NO
,DKKB.COU_NAME
,DKKB.INDV_TAX_NO
,DKKB.INDV_INSURS_NO
,DKKB.MN_INCO
,DKKB.ECON_RESUR
,DKKB.OTH_ECON_RESUR
,DKKB.DEPEND_CNT
,DKKB.AFF_INSTN_NO
,DKKB.EMP_FLG
,DKKB.POT_VIP_FLG
,DKKB.SPEC_VIP_FLG
,DKKB.INDV_CUST_ACCUM_TRN_LMT
,DKKB.CRED_CRD_GUAR_CNT
,DKKB.FAMI_AVG_MN_INCO
,DKKB.FAMI_CAPI
,DKKB.FAMI_DEBT
,DKKB.FAMI_MN_INCO
,DKKB.GRAD_DT
,DKKB.CHILD_FLG
,DKKB.INDUSTRY_TYP
,DKKB.FAMI_GUAR_TOTL
,DKKB.PLAN_CPTL_CERT_NO
,DKKB.CERT_TYP
,DKKB.CERT_NO
,DKKB.PRIM_NAT
,DKKB.RSDNT_NAT
,DKKB.CONC_CUST_FLG  --- 关注客户标志
,DKKB.IS_BLACK_LIST  -- 如果客户是黑名单用户也属于风险客户
,DKKB.INDV_LEV_COD  -- 征信等级不带A的为风险客户
,DKKB.CRLMT
,DKKB.CRED_LOTP


FROM BI_DW.F_ECIF_CUST_INFO DKKB
--- 如果客户是黑名单用户也属于风险客户
--征信等级不带A的为风险客户
WHERE IS_BLACK_LIST='是' OR 
EXISTS(SELECT 1 FROM BI_DW.F_ECIF_CUST_INFO B1 
WHERE INDV_LEV_COD NOT LIKE 'A%' AND DKKB.ECIF_CUST_NO=B1.ECIF_CUST_NO);
COMMIT;
END SP_FK;

--调用
BEGIN
  SP_FK();
END;

SELECT * FROM M_RISK_CUST_INFO

