--存储过程 全量更新至客户宽表
CREATE OR REPLACE PROCEDURE SP_KH 
IS
--创建日志变量
V_NAME VARCHAR2(20):='SP_KH';
V_ST DATE;  
V_ET DATE;
BEGIN
  V_ST := SYSDATE;
  --清空目标表F_ECIF_CUST_INFO客户宽表
EXECUTE IMMEDIATE ' TRUNCATE TABLE F_ECIF_CUST_INFO';
--向客户宽表新增数据
INSERT INTO F_ECIF_CUST_INFO 
SELECT 

KH.ECIF_CUST_NO
,KH.CUST_NAME
,KH.BIRTH_DT  --出生日期
,(CASE WHEN TRIM(SEX) = 1 THEN '男' 
 WHEN TRIM(SEX) = 2 THEN '女' ELSE '' END) AS SEX
,(SELECT NAME --婚姻状态
  FROM BI_ODS.O_LN_MABIAO
 WHERE MAZHI = 'DEM0100003'
   AND code = TRIM(KH.MRG_STS)
) MRG_STS 
,KH.REGISTER
,KH.PPL_COD --民族代码
,(SELECT NAME 
  FROM BI_ODS.O_LN_MABIAO
 WHERE MAZHI = 'DEM0100001'
   AND code = TRIM(KH.PPL_COD)) PPL_COD --民族名字
,KH.COU_CERT_NO
,KH.COU_NAME
,KH.RELIGION  --宗教信仰
,(SELECT NAME 
  FROM BI_ODS.O_LN_MABIAO
 WHERE MAZHI = 'DEM0100007'
   AND code = TRIM(EDUC_LEV)) EDUC_LEV  -- 教育
,KH.HOUSE_TYP
,KH.INDV_TAX_NO
,KH.INDV_INSURS_NO
,KH.HAVE_WORK_YR
,(SELECT CODE
  FROM BI_ODS.O_LN_MABIAO
 WHERE MAZHI = 'PAR0400044' AND TRIM(KH.OCCUP_COD) = TRIM(NAME)) AS OCCUP_COD  --职业
,QUALIFICATION_STS
,EMPLOYER_NAME
,UNIT_CHAR
,UNIT_WORK_DT
,WORK_NO  --工号
,(CASE TO_NUMBER(KH.POSN) WHEN 1 THEN '高级领导(行政级别局级及局级以上领导或大公司高级管理人员)'
      WHEN 2 THEN '中级领导(行政级别局级以下领导或大公司中级管理人员)'
      WHEN 3 THEN '一般员工'
      WHEN 4 THEN '其他'
      WHEN 9 THEN '未知' 
      END )AS POSN  ---职务
,OFRN
,(CASE TO_NUMBER(KH.TITL) WHEN 0001 THEN '无'
      WHEN 0002 THEN '高级'
      WHEN 0003 THEN '中级'
      WHEN 0004 THEN '初级'
      WHEN 9999 THEN '未知' 
      END )AS TITL  ---职称
,KH.MN_INCO
,KH.ECON_RESUR
,KH.OTH_ECON_RESUR
,KH.DEPEND_CNT
,KH.LANGUAGE_PRE
,KH.AFF_INSTN_NO
,KH.CUST_MNGR_COD
,KH.CUST_STS
,KH.EMP_FLG
,KH.POT_VIP_FLG
,KH.SPEC_VIP_FLG
,KH.INDV_CUST_ACCUM_TRN_LMT
,KH.CRED_CRD_GUAR_CNT
,KH.FAMI_AVG_MN_INCO
,KH.FAMI_CAPI
,KH.FAMI_DEBT
,KH.FAMI_MN_INCO
,KH.GRAD_DT   -- 毕业年月
,(CASE WHEN TRIM(CHILD_FLG) = 1 THEN '有' 
WHEN TRIM(CHILD_FLG) = 0 THEN '无' ELSE '' END) AS CHILD_FLG   
,(SELECT NAME
  FROM BI_ODS.O_LN_MABIAO  WHERE MAZHI = '100084' 
  AND CODE = TRIM(KH.INDUSTRY_TYP)) INDUSTRY_TYP  --从事行业类型
,KH.FAMI_GUAR_TOTL
,KH.PLAN_CPTL_CERT_NO
,KH.STUDY_INST
,KH.STUDY_SPEC
,KH.RESI_YR
,KH.CERT_TYP
,KH.CERT_NO
,KH.PRIM_NAT
,KH.RSDNT_NAT
,KH.CONC_CUST_FLG
,KH.BEST_CONT_TM
,KH.BEST_CONT_STY    --最佳联系方式
,(CASE WHEN exists( SELECT 1 FROM BI_ODS.O_CI_CIPH_HIGH_BLACK_LIST_INFO T WHERE KH.ECIF_CUST_NO=T.ECIF_CUST_NO)
      THEN '是'
        ELSE '否' END ) AS IS_BLACK_LIST   --判断黑名单
,HI1.INDV_LEV_COD
,HI1.CRLMT
,HI1.CRED_LOTP  --信用积分
,HIDR.ADDR_ID
      

FROM BI_ODS.O_CI_CIPH_HIGH_CUST_INFO KH
 -- 等级、额度、积分
LEFT JOIN (SELECT * FROM( 
SELECT ECIF_CUST_NO,INDV_LEV_COD,EVAL_DT,CRLMT,CRED_LOTP,
ROW_NUMBER()OVER(PARTITION BY ECIF_CUST_NO ORDER BY INDV_LEV_COD DESC ) PM
  FROM BI_ODS.O_CI_CIPH_HIGH_INDV_LEV_INFO ) HI WHERE HI.PM = 1
) HI1 ON HI1.ECIF_CUST_NO=KH.ECIF_CUST_NO 
--高端客户地址
LEFT JOIN (
SELECT ECIF_CUST_NO,ADDR_ID FROM BI_ODS.O_CI_CIPH_HIGH_PTY_ADDR_RELA)
HIDR ON HIDR.ECIF_CUST_NO=KH.ECIF_CUST_NO


--------------------
UNION
--------------------

--向客户宽表新增数据
SELECT 
KHL.ECIF_CUST_NO
,'NULL' AS CUST_NAME 
,BIRTH_DT
,(CASE WHEN TRIM(SEX) = 1 THEN '男' 
 WHEN TRIM(SEX) = 2 THEN '女' ELSE '' END) AS SEX
,(SELECT NAME --婚姻状态
  FROM BI_ODS.O_LN_MABIAO
 WHERE MAZHI = 'DEM0100003'
   AND code = TRIM(KHL.MRG_STS)
) MRG_STS
,REGISTER
,PPL_COD
,(SELECT NAME 
  FROM BI_ODS.O_LN_MABIAO
 WHERE MAZHI = 'DEM0100001'
   AND code = TRIM(KHL.PPL_COD)) PPL_COD --民族名字
,KHL.COU_CERT_NO
,KHL.COU_NAME
,KHL.RELIGION
,KHL.EDUC_LEV
,KHL.HOUSE_TYP
,KHL.INDV_TAX_NO
,KHL.INDV_INSURS_NO
,KHL.HAVE_WORK_YR
,KHL.OCCUP_COD
,KHL.QUALIFICATION_STS
,KHL.EMPLOYER_NAME
,KHL.UNIT_CHAR
,KHL.UNIT_WORK_DT
,KHL.WORK_NO
,KHL.POSN
,KHL.OFRN
,KHL.TITL
,KHL.MN_INCO
,KHL.ECON_RESUR
,KHL.OTH_ECON_RESUR
,KHL.DEPEND_CNT
,KHL.LANGUAGE_PRE
,KHL.AFF_INSTN_NO
,KHL.CUST_MNGR_COD
,KHL.CUST_STS
,KHL.EMP_FLG
,KHL.POT_VIP_FLG
,KHL.SPEC_VIP_FLG
,KHL.INDV_CUST_ACCUM_TRN_LMT
,KHL.CRED_CRD_GUAR_CNT
,KHL.FAMI_AVG_MN_INCO
,KHL.FAMI_CAPI
,KHL.FAMI_DEBT
,KHL.FAMI_MN_INCO
,KHL.GRAD_DT
,KHL.CHILD_FLG
,KHL.INDUSTRY_TYP
,KHL.FAMI_GUAR_TOTL
,KHL.PLAN_CPTL_CERT_NO
,KHL.STUDY_INST
,KHL.STUDY_SPEC
,KHL.RESI_YR
,KHL.CERT_TYP
,KHL.CERT_NO
,KHL.PRIM_NAT
,KHL.RSDNT_NAT
,KHL.CONC_CUST_FLG
,KHL.BEST_CONT_TM
,KHL.BEST_CONT_STY
  /*是否是黑名单
征信等级
信用额度
信用积分
联系地址ID
*/
,'' IS_BLACK_LIST
,'' INDV_LEV_COD
,0 CRLMT
,0 CRED_LOTP
,'' ADDR_ID
FROM BI_ODS.O_CI_CIPL_LOW_CUST_INFO KHL;
COMMIT;
--执行完结束时间
V_ET :=SYSDATE;
SP_MY_LOG(V_NAME,V_ST,V_ET,'','','成功');
--报错跳转
EXCEPTION
  --调用
  WHEN OTHERS THEN  V_ET :=SYSDATE;
  SP_MY_LOG(V_NAME,V_ST,V_ET,SQLCODE,SQLERRM,'异常');
END SP_KH;

--调用
BEGIN 
  SP_KH();
END;

SELECT * FROM F_ECIF_CUST_INFO 




CREATE TABLE MY_LOG(
   name varchar2(100),      --存储过程
   starttime date,          --存储过程执行的时间
   endtime date,            --存储过程结束的时间
   sql_code varchar2(100),  --存储过程错误编码
   sql_errmsg varchar2(255),--存储过程错误信息
   status varchar2(100)     --记录存储过程的状态
 );

  ----日志存储过程
  CREATE OR REPLACE PROCEDURE SP_MY_LOG(NAME      VARCHAR2,
                                        STARTDATE DATE,
                                        ENDDATE   DATE,
                                        SQL_CODE  VARCHAR2,
                                        SQL_ERRM  VARCHAR2,
                                        STATUS    VARCHAR2) IS
  /*****************************************************************************
     程序名称：SP_MY_LOG
     功能描述：日志表
     创 建 人：
     创建日期：
     修改日期：
     修改人员：
     修改原因：
  ******************************************************************************/
BEGIN
  INSERT INTO MY_LOG
  VALUES
    (NAME, STARTDATE, ENDDATE, SQL_CODE, SQL_ERRM, STATUS);
  COMMIT;
END;



SELECT * FROM MY_LOG












