--存储过程 全量更新至客户宽表
CREATE OR REPLACE PROCEDURE SP_KHLOW 
IS
BEGIN
--向客户宽表新增数据
INSERT INTO F_ECIF_CUST_INFO
SELECT 
KHL.ECIF_CUST_NO
,'NULL' AS CUST_NAME 
,BIRTH_DT
,(CASE WHEN TRIM(SEX) = 1 THEN '男' 
 WHEN TRIM(SEX) = 2 THEN '女' ELSE '' END) AS SEX
,MRG_STS
,REGISTER
,PPL_COD
,(SELECT NAME 
  FROM BI_ODS.O_LN_MABIAO
 WHERE MAZHI = 'DEM0100001'
   AND code = TRIM(KHL.PPL_COD)) PPL_COD --民族名字
,KHL.COU_CERT_NO
,KHL.COU_NAME
,KHL.RELIGION
,KHL.EDUC_LEV
,KHL.HOUSE_TYP
,KHL.INDV_TAX_NO
,KHL.INDV_INSURS_NO
,KHL.HAVE_WORK_YR
,KHL.OCCUP_COD
,KHL.QUALIFICATION_STS
,KHL.EMPLOYER_NAME
,KHL.UNIT_CHAR
,KHL.UNIT_WORK_DT
,KHL.WORK_NO
,KHL.POSN
,KHL.OFRN
,KHL.TITL
,KHL.MN_INCO
,KHL.ECON_RESUR
,KHL.OTH_ECON_RESUR
,KHL.DEPEND_CNT
,KHL.LANGUAGE_PRE
,KHL.AFF_INSTN_NO
,KHL.CUST_MNGR_COD
,KHL.CUST_STS
,KHL.EMP_FLG
,KHL.POT_VIP_FLG
,KHL.SPEC_VIP_FLG
,KHL.INDV_CUST_ACCUM_TRN_LMT
,KHL.CRED_CRD_GUAR_CNT
,KHL.FAMI_AVG_MN_INCO
,KHL.FAMI_CAPI
,KHL.FAMI_DEBT
,KHL.FAMI_MN_INCO
,KHL.GRAD_DT
,KHL.CHILD_FLG
,KHL.INDUSTRY_TYP
,KHL.FAMI_GUAR_TOTL
,KHL.PLAN_CPTL_CERT_NO
,KHL.STUDY_INST
,KHL.STUDY_SPEC
,KHL.RESI_YR
,KHL.CERT_TYP
,KHL.CERT_NO
,KHL.PRIM_NAT
,KHL.RSDNT_NAT
,KHL.CONC_CUST_FLG
,KHL.BEST_CONT_TM
,KHL.BEST_CONT_STY
  /*是否是黑名单
征信等级
信用额度
信用积分
联系地址ID
*/
,'' IS_BLACK_LIST
,'' INDV_LEV_COD
,'' CRLMT
,'' CRED_LOTP
,'' ADDR_ID


FROM BI_ODS.O_CI_CIPL_LOW_CUST_INFO KHL;
END;


BEGIN 
  SP_KHLOW();  --存数据
END;

SELECT * FROM F_ECIF_CUST_INFO 
