--存储过程 全量更新至贷款宽表
CREATE OR REPLACE PROCEDURE SP_DK 
IS
BEGIN
  --清空贷款宽表 
  EXECUTE IMMEDIATE 'TRUNCATE TABLE F_LN_LION_INFO';
  --插入数据
  INSERT INTO F_LN_LION_INFO 
  SELECT 
  DK.LOANACNO
  ,DK.ECIF_CUST_NO
  ,DK.CUSTNAME --客户姓名
  ,(SELECT TRIM(MRG_STS) FROM F_ECIF_CUST_INFO 
  WHERE ECIF_CUST_NO = DK.ECIF_CUST_NO) AS MRG_STS --婚姻字段 在客户宽表当中 先填空
  ,(SELECT NAME FROM BI_ODS.O_LN_MABIAO 
  WHERE MAZHI='ACC1300012' AND CODE=DK.CURRSIGN) CURRSIGN --货币转换
  ,(SELECT NAME FROM BI_ODS.O_LN_MABIAO 
  WHERE MAZHI='053' AND CODE=TRIM(DK.LOANKIND)) LOANKIND --贷款种类
  ,CASE WHEN DK.LOANTYPE = 1 THEN '是'
  ELSE '否' END AS LOANTYPE  --贷款标志
  ,FIRSTORDER
  ,PAYPERC
  ,FUNDSOUR
  ,LOANUSE
  ,ASSUKIND
  ,CONTDATE
  ,CREDCAPI
  ,CYCFLAG  --是否循环
  ,FK.放款总金额
  ,HK.还款总金额
  ,TCAPI-HK.还款本金 AS LN_BALANCE --贷款余额
  ,TCAPI
  ,THISTCAPI  --开户放款金额
  ,ED.CREDAMT
  ,ED.ASSUAMT
  ,ED.IMPAAMT
  ,ED.MORTAMT
  ,ED.CREDTOTALAMT  --授信总额度
  ,DK.TERMFREQ
  ,DK.TTERM
  ,DK.RETUTYPE
  ,DK.TROTHDUEDAY
  ,DK.FIXRATETERM
  ,DK.FIRSTDUEDATE
  ,DK.SUBSFLAG
  ,DK.ISENOUSUBS
  ,DK.FIRSTPAYAMT
  ,DK.FIRSTPAYPERC
  ,DK.RELEWAY
  ,DK.PAYEEACNO
  ,DK.PAYEEACNAME
  ,DK.PAYEEBANKNAME
  ,DK.INTECALCKIND
  ,DK.INTEMETH
  ,DK.INTEBASE
  ,DK.AHEADDAYS
  ,DK.BASICINTERATE
  ,DK.INTERATE
  ,DK.BEGINDATE
  ,DK.ENDDATE
  ,DK.APPRNAME
  ,DK.APPRTABNO
  ,DK.APPRDATE
  ,DK.APPRFLAG
  ,DK.APPRSTATE
  ,DK.LOANSTATE
  
  FROM BI_ODS.O_LN_LNP_CTRT_CBAPP DK
  LEFT JOIN (SELECT RT_CUST_NUM, SUM(TR_TRAN_AMT) 放款总金额
--个人贷款放款流水档
  FROM BI_ODS.O_LN_LNP_ACCT_AMWKPL06
 GROUP BY RT_CUST_NUM
) FK ON FK.RT_CUST_NUM=DK.LOANACNO  --关联贷款账户
  LEFT JOIN (SELECT RT_ACCT_NUM,
       SUM(PRIN_PAY_AMT + INT_PAY_AMT) 还款总金额,
       SUM(PRIN_PAY_AMT) 还款本金
       --个人贷款还款流水档
  FROM BI_ODS.O_LN_LNP_ACCT_AMWKPL07
 GROUP BY RT_ACCT_NUM) HK ON HK.RT_ACCT_NUM=DK.LOANACNO --关联贷款账户
 LEFT JOIN ( 
SELECT *
  FROM (SELECT --个人贷款客户额度管理档
         ECIF_CUST_NO,
         CREDAMT,
         ASSUAMT,
         IMPAAMT,
         MORTAMT,
         CREDTOTALAMT,
         APPRDATE,
         ROW_NUMBER() OVER(PARTITION BY ECIF_CUST_NO ORDER BY APPRDATE DESC) PM
        
          FROM BI_ODS.O_LN_LNP_CUST_CBCREDCUST) T
 WHERE T.PM = 1
)
  ED ON ED.ECIF_CUST_NO=DK.ECIF_CUST_NO;
COMMIT;
END;

--调用
BEGIN
  SP_DK();
END;

--查寻贷款宽表
SELECT * FROM F_LN_LION_INFO;

