   
--将scott用户里面，EMP1和DEPT1表中所有不够200长度的varchar2数据类型，
--长度修改为200
  表字段信息表：user_tab_columns(数据字典)  
SELECT * FROM USER_TAB_COLUMNS WHERE TABLE_NAME IN('EMP1','DEPT1')
AND DATA_TYPE = 'VARCHAR2'AND LENGTH(DATA_TYPE)<200;     

ALTER TABLE EMP1 MODIFY 字段 VARCHAR2(200);   ---DDL修改表

DECLARE
  CURSOR C_A IS
    SELECT TABLE_NAME,COLUMN_NAME, DATA_TYPE
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME IN ('EMP1', 'DEPT1')
       AND DATA_TYPE = 'VARCHAR2'
       AND LENGTH(DATA_TYPE) < 200;
BEGIN
FOR I IN C_A
    DBMS_OUTPUT.put_line(I.COLUMN_NAME);
    EXECUTE IMMEDIATE 'ALTER TABLE ' || I.TABLE_NAME ||' MODIFY ' ||I.COLUMN_NAME||' VARCHAR2(200)';
    DBMS_OUTPUT.put_line(LENGTH(I.COLUMN_NAME));
    DBMS_OUTPUT.put_line(LENGTH(I.COLUMN_NAME));
END;


