--递归查询

--查寻SMITH的上司
SELECT *
  FROM EMP
 WHERE EMPNO = (SELECT MGR FROM EMP WHERE ENAME = 'SMITH');

--查询SMITH的顶级上司

SELECT * FROM EMP FOR UPDATE


--语法结构
CONNECT BY 指定匹配逻辑(父子级关系)
LEVEL      层级 
START WITH 起始位置
PRIOR      指定父级


--构建序列  生成一列我们指定行数的数字
SELECT LEVEL FROM DUAL CONNECT BY LEVEL < 10;

--数据爆炸
SELECT DISTINCT LEVEL FROM EMP  CONNECT BY LEVEL < 6;

SELECT POWER(14,1)+POWER(14,2)+POWER(14,3)+POWER(14,4)
+POWER(14,5) FROM DUAL;


--生成上下级关系]

SELECT E.*, LEVEL
  FROM EMP E
 START WITH MGR IS NULL
CONNECT BY MGR = PRIOR EMPNO
 ORDER BY LEVEL;
